### PR TITLE
Use Scala concurrency to improve performance

### PR DESCRIPTION
**Pull request by alankstewart**

### CODE REVIEW

**Comment by cdupuis** [comment]
How many threads is this creating? What happens if two archives get unpacked at the same time?

**Comment by alankstewart** [comment]
According to the Scala docs (http://docs.scala-lang.org/overviews/core/futures.html), 
> the ExecutionContext.global sets the parallelism level of its underlying fork-join pool to the amount of available processors.
I experiment with varying thread pool sizes but using the default seem to give the best performance over multiple runs. I am writing more tests and tweaking the code.

**Comment by ddgenome** [comment]
Why was the timeout decreased to 15 s? Have you tested with archives having lots of files and large size?

**Comment by alankstewart** [comment]
There was concern by Christian that four seconds was too long for an archive

**Pull request merged**
